//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapıMarket2.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satıs
    {
        public int SatısID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> Musteri { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> Fiyat { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
